### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by nippoo** [fjullien/rnif2ki#2]
Hey, just to note I've ported this over to Python in case it helps anyone! Thanks for writing this converter!

(P.S. désolé, je l’ai réécrit en anglais... !)

https://github.com/nippoo/rinf2kicad/tree/main

**Comment by fjullien** [comment]
I'm glad this project is useful after 16 years :)
At that time, I was young, wrote all comment and variable in French, I didn't know it could be an international project.
Anyway, that awesome!
